CREATE TABLE hash
(
    hash VARCHAR(16) NOT NULL,
    cid INTEGER NOT NULL,
    time SMALLINT NOT NULL
);

CREATE TABLE cid
(
    cid INTEGER NOT NULL PRIMARY KEY,
    bvid VARCHAR(16) NOT NULL,
    epid INTEGER NOT NULL,
    name VARCHAR(64) NOT NULL
);

CREATE INDEX idx_hash
ON hash (hash);

/* CREATE TABLE request
(
    qid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    img_path VARCHAR(64) NOT NULL
); */