CREATE TABLE frames
(
    frame_id INTEGER PRIMARY KEY,
    cid INTEGER NOT NULL,
    time REAL NOT NULL
);

CREATE TABLE cid
(
    cid INTEGER NOT NULL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    season_id INTEGER NOT NULL,
    info VARCHAR(128) NOT NULL
);
